### ISSUE TITLE
尝试留言时，系统抛出异常

### ISSUE THREAD

**Issue by JacksionGT** [eurooooo/zephyrlin.me#1]
我不确定是否只有我自己发现了这个bug，但是我经过多次尝试发现，这个bug是可以复现的。
我使用以下2款浏览器分别进行尝试：
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
具体的操作细节和页面反馈的异常信息如下图：
<img width="611" alt="无标题" src="https://github.com/user-attachments/assets/c436a687-4148-454b-ad17-bd1da82cb4a4">

**Comment by eurooooo** [comment]
首先非常感谢你对我的网站的宝贵意见，我会认真考虑的。
同时这个bug也很有价值，我刚刚修复了这个bug，现在你应该可以留言了。
