### ISSUE TITLE
复现过程中卡在sanity无法登陆成功

### ISSUE THREAD

**Issue by ShaneLau2** [eurooooo/zephyrlin.me#2]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/e4c1bc30-5895-4d14-98e2-b4eb68842b5c">
如图所示, 一直在转圈, 三种登陆方式都尝试过了

**Comment by ShaneLau2** [comment]
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/4c00e68f-c92e-477b-b4a3-a39a71ebc713">
补充图片

**Comment by eurooooo** [comment]
你有创建sanity账号吗

**Comment by ShaneLau2** [comment]
有账号, 我能想到唯一的问题可能是我的运行环境是docker, 链接可以访问, 但是重定向到过程中会产生错误
<img width="806" alt="image" src="https://github.com/user-attachments/assets/3f8962b8-9d68-48d8-a787-246c14081afb">

**Comment by eurooooo** [comment]
先把/sanity那个文件夹删除，再试着重新运行一下命令行？
